version: "3.9"

services:
  db:
    image: postgres:17
    container_name: passkey_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: passkey_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: passkey_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: passkey_db
      DB_PORT: 5432
      PORT: 8080
      ENV: development
      RP_ID: localhost
      RP_ORIGINS: http://localhost:6334,http://localhost:8080
    ports:
      - "8080:8080"
    restart: always

  manual_test:
    build:
      context: ./manual-test
    container_name: manual_test_server
    ports:
      - "6334:6334"
    restart: always

volumes:
  db_data:

